### ISSUE TITLE
Include `dist` into repository

### ISSUE THREAD

**Issue by sftsk** [anttiviljami/wp-server-log-viewer#2]
At the moment setting up the plugin does not work out of the box. Need to run `gulp` manually to have js loaded to set up new log file.

**Comment by anttiviljami** [comment]
Dist is in the releases zip file. :) I'm not planning to add compiled assets to the repo

**Comment by anttiviljami** [comment]
I should fix the download link in readme though.. thanks!

**Comment by anttiviljami** [comment]
Actually, when installing via composer this should just work. I guess I need to add some sort of installation script.. That would however require nodejs In the environment.

You're right. I should just include the dist in the repo

**Comment by sftsk** [comment]
:) thanks!
